rm -rf agents/target
rm -rf agents/target-ide
rm -rf agents/.classpath
rm -rf agents/.project
rm -rf agents/.settings
rm -rf agents/.gitignore
rm -rf agents/node1/
rm -rf agents/node2/
rm -rf mdsal/target
rm -rf mdsal/target-ide
rm -rf mdsal/.classpath
rm -rf mdsal/.project
rm -rf mdsal/.settings
rm -rf mdsal/.gitignore
rm -rf mdsal/src/main/yang-gen-sal
rm -rf network/target
rm -rf network/target-ide
rm -rf network/.classpath
rm -rf network/.project
rm -rf network/.settings
rm -rf network/.gitignore
rm -rf serialization/target
rm -rf serialization/target-ide
rm -rf serialization/.classpath
rm -rf serialization/.project
rm -rf serialization/.settings
rm -rf serialization/.gitignore
rm -rf store/target
rm -rf store/target-ide
rm -rf store/.classpath
rm -rf store/.project
rm -rf store/.settings
rm -rf store/.gitignore
rm -rf target
rm -rf .project
rm -rf .settings
rm -rf store/JDBC-Connection/
rm -rf .metadata/
rm -rf RemoteSystemsTempFiles/
rm -rf agents/bin/
rm -rf network/bin/
rm -rf serialization/bin/
rm -rf store/bin/
rm -rf store/src/main/yang-gen-sal/
rm -rf src
